id: fd98fa7db45d49f8b5bd277fef19f994
initial_creation_type: ocr
source_metadata:
  volumes:
    fa08f67af8ae4327b1a10ade5c7fc51e:
      base_file: v057.txt
      image_group_id: I1PD95903
      title: དབུ་མའི་དོན་བསྡུས་པ།
      total_pages: 1649
      volume_number: 58
